development:
  access_key_id: AKIAIL624GTXITLAR7MA
  secret_code: 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
production:
  access_key_id: AKIAIL624GTXITLAR7MA
  secret_code: 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